### ISSUE TITLE
Space Rocks arcade crash

### ISSUE THREAD

**Issue by nowakowsk** [Elatronion/televoid#1]
Game crashed when destroying the last asteroid.

Console output:
```
[Runtime Error] Subscript out of bounds.
[main line 296] in bullet_hit_logic(_)
[main line 350] in update(_)
```

**Comment by nowakowsk** [comment]
More info: it happened to me once in Windows build. Next time I won Space Rocks nothing crashed, but I didn't get the ticket for winning.

**Comment by Elatronion** [comment]
Thank you for the bug report, this is a new experience for me! :D
To fix the problem temporarily, I'll revert to an older version of the minigame that I know should work on Windows.

**Comment by nowakowsk** [comment]
No problem, I'm really enjoying the game. :)

**Comment by Elatronion** [comment]
Well, the new version is up on GameJolt and pushed here!
Hopffully there aren't too many other issues, let me know if you find any more! :)

**Comment by nowakowsk** [comment]
This seem to have solved the issue, thanks!
